### ISSUE TITLE
set anither domaine

### ISSUE THREAD

**Issue by VirgileDjimgou** [ncjones/python-guerrillamail#13]
hi :) , 

i want to know  if it is possible to set another domaine server ...for exampel grr.la  or pokemail.net ....if yes how to do that ?  ....

**Comment by do-n-khanh** [comment]
i have the same question. 
have you figured out how to do it?

**Comment by VirgileDjimgou** [comment]
unfortunately I still have no solution ....

**Comment by VirgileDjimgou** [comment]
unfortunately I still have no solution ....

**Comment by ncjones** [comment]
You can configure the base URL for the API calls to your custom Guerillamail server. This is documented in the readme.

The domain name of your email address should not matter - Guerillamail inboxes are identified by email address local part only.

If this does not help then please explain exactly what you are experiencing.

**Comment by do-n-khanh** [comment]
thanks for reply. i solved the problem. 

just simple send email to any domain of guerrilla domain (grr.la, spam4.me, etc), and then we can get the email.
