### ISSUE TITLE
Sending

### ISSUE THREAD

**Issue by yacob841** [ncjones/python-guerrillamail#5]
I don't see any send functions in your lib. I'm guessing that is because it's pretty easy to send an email but the issue I am having is the correct server. So I am using the SMTP server that I saw was used by the GuerrillaMail website, it's pretty inconsistent. When I send to gmail, it says it sends but I never get it. If I send to a GuerrillaMail email it sends and I receive. When I send to an exchange or iCloud my try catches an exception. Any ideas?

**Comment by ncjones** [comment]
I have never set up an SMTP server so I am not in the best position to help you with with this issue. Maybr Gmail is blocking your messages because they look like they come from an illegitimate email server. Can you use the Gmail SMTP server instead of running your own?

**Comment by yacob841** [comment]
I doubt that is the reason because it should be the same server as the one used on the guerrillamail website, which if I send from there to my gmail it works fine.  Also, if I use the Gmail SMTP it requires me to login to an account, which I would rather not. But thanks anyways!

On a different note, another thing I didn't see but I was wondering about was if there is a function to delete emails? I have a workaround of me putting the emails into an array and only showing the array, that way I can just remove the email from the array and it will appear to be gone, but I would prefer to do it the correct way lol. Thanks for you work BTW!
