### ISSUE TITLE
grr.la API Connection Error CLI

### ISSUE THREAD

**Issue by nmbarker** [ncjones/python-guerrillamail#6]
I'd like to use the grr.la extension because in my opinion it looks better than the other extensions. The JSON file has { "base_url": "https://api.grr.la", } in it. (Sorry for the format I have background in java). Is there any api for this address?

**Comment by ncjones** [comment]
The base URL for API calls and the domain you use for the temporary email addresses are distinct. In your case you should be able to send email to your grr.la address and receive them using the default API base URL setting.

**Comment by VirgileDjimgou** [comment]
hello Mr Jones  , please can  you explain me how to setup another extension like for example  grr.la   ??

**Comment by ncjones** [comment]
It should just work. Can you explain what you have tried and what is the
expected behavior?
