### ISSUE TITLE
Setting custom suffix to email

### ISSUE THREAD

**Issue by k9thebeast** [ncjones/python-guerrillamail#7]
Is it possible to change the @guerrillamailblock.com to any of the other defaults? AKA (pokemail.com?) Or how would I change it to my custom domain.

Thanks!

**Comment by ncjones** [comment]
The domain names used by the official Guerillamail server are aliases. Although the CLI shows "xyz@guerrillamailblock.com" as your email when running the "info" command, emails sent to any of the aliases (eg xyz@pokemail.net or xyz@sharklasers.com) will appear in the same inbox. This is why the "setaddr" command ignores any supplied domain name. 

See also #2.
